language: node_js

node_js: stable

install:
  - npm install

script:
  - hexo clean
  - hexo generate
  - npm run eslint
  - npm run build

after_script:
  - cd ./public
  - git init
  - git config user.name "xiaolony"
  - git config user.email "xiaolony@hotmail.com"
  - git add .
  - git commit -m "pulish some articles"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - gh-pages
env:
 global:
   - GH_REF: github.com/xiaolony/xiaolony.github.io.git
